const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.TiledBg,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.jumpthru,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Behaviors.Sin.Exps.CyclePosition,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{Plataforma: 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{Jogador: 0},
	{agua: 0},
	{Senóide: 0},
	{Inimigo: 0},
	{objetivo: 0},
	{Fase2: 0},
	{Texto: 0},
	{Botão2: 0},
	{JogadorAni: 0},
	{Teclado: 0},
	{Moeda: 0},
	{Pontos: 0},
	{Áudio: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Sólido: 0},
	{Terreno: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{PularAtravés: 0},
	{Mosaico: 0},
	{Mosaico2: 0},
	{nuvem: 0},
	{seta: 0}
];

self.InstanceType = {
	Jogador: class extends self.ISpriteInstance {},
	agua: class extends self.ISpriteInstance {},
	Inimigo: class extends self.ISpriteInstance {},
	objetivo: class extends self.ISpriteInstance {},
	Fase2: class extends self.ITextInstance {},
	Texto: class extends self.ITextInstance {},
	Botão2: class extends self.IButtonInstance {},
	JogadorAni: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Moeda: class extends self.ISpriteInstance {},
	Pontos: class extends self.ITextInstance {},
	Áudio: class extends self.IInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Terreno: class extends self.ITilemapInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	Mosaico: class extends self.ITilemapInstance {},
	Mosaico2: class extends self.ITilemapInstance {},
	nuvem: class extends self.ITilemapInstance {},
	seta: class extends self.ITilemapInstance {}
}